# Sourcing Files

# Monitors
source = ~/.config/hypr/modules/monitors.conf

# Programs
source = ~/.config/hypr/modules/programs.conf

# Auto Start
source = ~/.config/hypr/modules/autostart.conf

# Enviroment Variables
source = ~/.config/hypr/modules/envvar.conf

# Decorations
source = ~/.config/hypr/modules/decor.conf

#Animations
source = ~/.config/hypr/modules/anim.conf

# Window Rules
source = ~/.config/hypr/modules/winrules.conf

# Layout Rules
source = ~/.config/hypr/modules/layout.conf

# Input
source = ~/.config/hypr/modules/input.conf

# Keybinding
source = ~/.config/hypr/modules/keybind.conf

# Misc
source = ~/.config/hypr/modules/misc.conf