# Auto Start
# Autostart necessary processes (like notifications daemons, status bars, etc.)

# Daemons
exec-once = awww-daemon
exec-once = ags run .config/ags

# Obsidian
windowrule = workspace special:note silent, match:class ^(obsidian)$
exec-once = obsidian

# Terminal
exec-once = [workspace special:terminal silent] kitty
exec-once = [workspace special:terminal silent] kitty -e btop
