# Layout Rules
# See https://wiki.hypr.land/Configuring/Dwindle-Layout/

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/

master {
    new_status = master
}
